# Generated by Django 4.2.8 on 2024-02-03 19:24

from django.db import migrations, models
import files.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=files.upload.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='время загрузки файла')),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
